// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonTCG.API.Data;

#nullable disable

namespace PokemonTCG.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926125601_SetGoals")]
    partial class SetGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("PokemonTCG.API.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_guest");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PokemonTCG.API.Data.Card", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Artist")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("artist");

                    b.Property<string>("FlavorText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("flavor_text");

                    b.Property<string>("Hp")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("hp");

                    b.Property<string>("ImageLarge")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_large");

                    b.Property<string>("ImageSmall")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_small");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("NationalDex")
                        .HasColumnType("integer")
                        .HasColumnName("national_dex");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("number");

                    b.Property<string>("Rarity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rarity");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("set_id");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("set_name");

                    b.Property<int?>("SetPrintedTotal")
                        .HasColumnType("integer")
                        .HasColumnName("set_printed_total");

                    b.Property<DateOnly?>("SetReleased")
                        .HasColumnType("date")
                        .HasColumnName("set_released");

                    b.Property<string>("SetSeries")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("set_series");

                    b.PrimitiveCollection<string[]>("Subtypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("subtypes");

                    b.Property<string>("Supertype")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("supertype");

                    b.Property<int?>("TcgplayerProductId")
                        .HasColumnType("integer")
                        .HasColumnName("tcgplayer_product_id");

                    b.Property<string>("TcgplayerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tcgplayer_url");

                    b.PrimitiveCollection<string[]>("Types")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("types");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("PokemonTCG.API.Data.CardSet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PrintedTotal")
                        .HasColumnType("integer")
                        .HasColumnName("printed_total");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("series");

                    b.Property<string>("SymbolUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("symbol_url");

                    b.Property<int?>("TcgplayerGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("tcgplayer_group_id");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("sets", (string)null);
                });

            modelBuilder.Entity("PokemonTCG.API.Data.CollectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AcquiredOn")
                        .HasColumnType("date")
                        .HasColumnName("acquired_on");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("card_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("condition");

                    b.Property<decimal?>("CostEach")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cost_each");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("variant");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId", "CardId", "Variant", "Condition")
                        .IsUnique();

                    b.ToTable("collection_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_collection_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("PokemonTCG.API.Data.LatestPrice", b =>
                {
                    b.Property<string>("CardId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("card_id");

                    b.Property<string>("Variant")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("variant");

                    b.Property<decimal?>("High")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("high");

                    b.Property<decimal?>("Low")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("low");

                    b.Property<decimal?>("Market")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("market");

                    b.Property<decimal?>("Mid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("mid");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.HasKey("CardId", "Variant");

                    b.ToTable("latest_prices", (string)null);
                });

            modelBuilder.Entity("PokemonTCG.API.Data.PredictionRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AsOf")
                        .HasColumnType("date")
                        .HasColumnName("as_of");

                    b.Property<double?>("BaselineMae")
                        .HasColumnType("double precision")
                        .HasColumnName("baseline_mae");

                    b.Property<bool>("Checkpoint")
                        .HasColumnType("boolean")
                        .HasColumnName("checkpoint");

                    b.Property<double?>("DirectionAccuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("direction_accuracy");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("horizon_days");

                    b.Property<string>("Importance")
                        .HasColumnType("jsonb")
                        .HasColumnName("importance");

                    b.Property<double?>("Mae")
                        .HasColumnType("double precision")
                        .HasColumnName("mae");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<int>("Predictions")
                        .HasColumnType("integer")
                        .HasColumnName("predictions");

                    b.Property<double?>("RealizedBaselineMae")
                        .HasColumnType("double precision")
                        .HasColumnName("realized_baseline_mae");

                    b.Property<int?>("RealizedCount")
                        .HasColumnType("integer")
                        .HasColumnName("realized_count");

                    b.Property<double?>("RealizedDirectionAccuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("realized_direction_accuracy");

                    b.Property<double?>("RealizedMae")
                        .HasColumnType("double precision")
                        .HasColumnName("realized_mae");

                    b.Property<double?>("ResidualHigh")
                        .HasColumnType("double precision")
                        .HasColumnName("residual_high");

                    b.Property<double?>("ResidualLow")
                        .HasColumnType("double precision")
                        .HasColumnName("residual_low");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("TrainingRows")
                        .HasColumnType("integer")
                        .HasColumnName("training_rows");

                    b.Property<int>("ValidationRows")
                        .HasColumnType("integer")
                        .HasColumnName("validation_rows");

                    b.HasKey("Id");

                    b.ToTable("prediction_runs", (string)null);
                });

            modelBuilder.Entity("PokemonTCG.API.Data.PricePrediction", b =>
                {
                    b.Property<int>("RunId")
                        .HasColumnType("integer")
                        .HasColumnName("run_id");

                    b.Property<string>("CardId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("card_id");

                    b.Property<string>("Variant")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("variant");

                    b.Property<double>("ChangePercent")
                        .HasColumnType("double precision")
                        .HasColumnName("change_percent");

                    b.Property<decimal>("Current")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("current");

                    b.Property<decimal>("High")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("low");

                    b.Property<decimal>("Predicted")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("predicted");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons");

                    b.HasKey("RunId", "CardId", "Variant");

                    b.HasIndex("CardId", "RunId");

                    b.ToTable("price_predictions", (string)null);
                });

            modelBuilder.Entity("PokemonTCG.API.Data.PriceSnapshot", b =>
                {
                    b.Property<string>("CardId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("card_id");

                    b.Property<string>("Variant")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("variant");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal?>("High")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("high");

                    b.Property<decimal?>("Low")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("low");

                    b.Property<decimal?>("Market")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("market");

                    b.Property<decimal?>("Mid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("mid");

                    b.HasKey("CardId", "Variant", "Date");

                    b.HasIndex("Date");

                    b.ToTable("price_snapshots", (string)null);
                });

            modelBuilder.Entity("PokemonTCG.API.Data.SetGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("set_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.HasIndex("UserId", "SetId")
                        .IsUnique();

                    b.ToTable("set_goals", (string)null);
                });

            modelBuilder.Entity("PokemonTCG.API.Data.SnapshotRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardsSeen")
                        .HasColumnType("integer")
                        .HasColumnName("cards_seen");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("PricesWritten")
                        .HasColumnType("integer")
                        .HasColumnName("prices_written");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("snapshot_runs", (string)null);
                });

            modelBuilder.Entity("PokemonTCG.API.Data.WishlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("card_id");

                    b.Property<decimal?>("TargetPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("target_price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Variant")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("variant");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId", "CardId")
                        .IsUnique();

                    b.ToTable("wishlist_items", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PokemonTCG.API.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PokemonTCG.API.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PokemonTCG.API.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonTCG.API.Data.CollectionItem", b =>
                {
                    b.HasOne("PokemonTCG.API.Data.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonTCG.API.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonTCG.API.Data.LatestPrice", b =>
                {
                    b.HasOne("PokemonTCG.API.Data.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonTCG.API.Data.PricePrediction", b =>
                {
                    b.HasOne("PokemonTCG.API.Data.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonTCG.API.Data.PredictionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonTCG.API.Data.PriceSnapshot", b =>
                {
                    b.HasOne("PokemonTCG.API.Data.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonTCG.API.Data.SetGoal", b =>
                {
                    b.HasOne("PokemonTCG.API.Data.CardSet", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonTCG.API.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonTCG.API.Data.WishlistItem", b =>
                {
                    b.HasOne("PokemonTCG.API.Data.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonTCG.API.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
